import pkg from '/opt/node22/lib/node_modules/playwright/index.js';
const { chromium } = pkg;
import { pathToFileURL } from 'url';
const b = await chromium.launch();
const p = await b.newPage({ viewport:{width:1240,height:1180}, deviceScaleFactor:1 });
await p.goto(pathToFileURL(process.cwd()+'/mockups/configurator.html').href,{waitUntil:'networkidle'});
let n=0;
const snap = async (wait=650)=>{ await p.waitForTimeout(wait); await p.screenshot({path:`/tmp/frame_${String(n++).padStart(2,'0')}.png`}); };
const click = async (sel)=>{ await p.locator(sel).first().click(); };
await snap(400);
await click('.grp.drawerbox button:has-text("24")'); await snap();
await click('[data-group="wood"] button[data-name="White Oak"]'); await snap();
await click('#ptabs button[data-prod="drawerunit"]'); await snap(550);
await click('.grp.drawerunit button:has-text("5")'); await snap();
await click('.grp.drawerunit button:has-text("Undermount")'); await snap();
await click('#ptabs button[data-prod="cabinetdoor"]'); await snap(550);
await click('.grp.cabinetdoor button:has-text("Raised")'); await snap();
await click('#ptabs button[data-prod="shelf"]'); await snap(750);
await b.close(); console.log('captured', n, 'frames');
